/**
 * 完整的YouTube Cookies获取脚本
 * 在YouTube页面的浏览器控制台中运行
 * 获取更完整的认证cookies
 */

// 完整版cookies提取脚本
(function() {
    console.log('🍪 完整版YouTube Cookies提取工具');
    console.log('📋 使用说明：');
    console.log('1. 确保已登录YouTube账户');
    console.log('2. 观看几个视频，进行一些操作');
    console.log('3. 运行此脚本');
    console.log('');
    
    window.getCompleteYouTubeCookies = function() {
        console.log('🔍 开始扫描所有cookies...');
        
        // 检查登录状态
        const isLoggedIn = document.cookie.includes('SAPISID') || 
                          document.cookie.includes('__Secure-3PSID') ||
                          document.cookie.includes('LOGIN_INFO');
        
        if (!isLoggedIn) {
            console.log('❌ 检测到未登录状态');
            console.log('💡 请先登录YouTube账户，然后重新运行脚本');
            return null;
        }
        
        console.log('✅ 检测到已登录状态');
        
        // 获取所有cookies
        const allCookies = document.cookie.split(';');
        
        // 所有重要的YouTube和Google cookies
        const importantCookies = [
            // 基础认证
            'VISITOR_INFO1_LIVE',
            'YSC',
            'PREF',
            'CONSENT',
            'SOCS',
            
            // 安全认证
            '__Secure-3PSID',
            '__Secure-3PAPISID',
            '__Secure-3PSIDCC',
            '__Secure-1PSID',
            '__Secure-1PAPISID',
            '__Secure-1PSIDCC',
            
            // 会话认证
            'HSID',
            'SSID',
            'APISID',
            'SAPISID',
            'SID',
            'SIDCC',
            
            // 登录信息
            'LOGIN_INFO',
            'SESSION_TOKEN',
            
            // YouTube特定
            '__Secure-YT_TVFAS',
            '__Secure-ROLLOUT_TOKEN',
            'DEVICE_INFO',
            'VISITOR_PRIVACY_METADATA',
            '__Secure-YT_DERP',
            
            // 其他重要
            'NID',
            'DV',
            '1P_JAR'
        ];
        
        let cookiesText = '# Netscape HTTP Cookie File\n';
        cookiesText += '# This file is generated by YouTube cookies extractor\n';
        cookiesText += '# Generated on: ' + new Date().toISOString() + '\n\n';
        
        let foundCookies = 0;
        let foundImportant = 0;
        
        allCookies.forEach(cookie => {
            const [name, value] = cookie.trim().split('=');
            if (name && value) {
                const isImportant = importantCookies.some(important => 
                    name.includes(important) || important.includes(name)
                );
                
                if (isImportant) {
                    // 确定域名
                    let domain = '.google.com';
                    if (name.includes('YT') || name.includes('VISITOR') || name.includes('YSC')) {
                        domain = '.youtube.com';
                    }
                    
                    const flag = 'TRUE';
                    const path = '/';
                    const secure = name.includes('Secure') ? 'TRUE' : 'FALSE';
                    const expiration = Math.floor(Date.now() / 1000) + (365 * 24 * 60 * 60); // 1年后过期
                    
                    cookiesText += `${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${name}\t${value}\n`;
                    foundImportant++;
                }
                foundCookies++;
            }
        });
        
        console.log(`📊 扫描结果：`);
        console.log(`   总cookies数量: ${foundCookies}`);
        console.log(`   重要cookies数量: ${foundImportant}`);
        
        if (foundImportant < 5) {
            console.log('⚠️ 重要cookies数量较少，建议：');
            console.log('1. 观看几个YouTube视频');
            console.log('2. 点击一些频道和播放列表');
            console.log('3. 进行搜索操作');
            console.log('4. 重新运行此脚本');
            console.log('');
        }
        
        console.log('📋 Cookies内容：');
        console.log('='.repeat(80));
        console.log(cookiesText);
        console.log('='.repeat(80));
        
        // 自动下载
        try {
            const blob = new Blob([cookiesText], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'youtube_cookies_complete.txt';
            a.style.display = 'none';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            console.log('💾 完整cookies文件已下载！');
        } catch (error) {
            console.log('⚠️ 自动下载失败，请手动复制上面的内容');
        }
        
        // 复制到剪贴板
        try {
            navigator.clipboard.writeText(cookiesText).then(() => {
                console.log('📋 Cookies已复制到剪贴板！');
            }).catch(() => {
                console.log('⚠️ 无法复制到剪贴板，请手动复制');
            });
        } catch (error) {
            console.log('⚠️ 剪贴板不可用，请手动复制');
        }
        
        // 提供使用建议
        console.log('');
        console.log('🎯 下一步操作：');
        console.log('1. 将cookies内容粘贴到视频下载器');
        console.log('2. 等待1-2分钟后再测试（避免频率限制）');
        console.log('3. 如果仍然失败，可能需要更换IP或等待更长时间');
        
        return cookiesText;
    };
    
    console.log('🚀 脚本已加载！运行命令: getCompleteYouTubeCookies()');
})();
